logging:
  level:
    root: info

    # Maze
    tech.maze: info

    # Database
    org.hibernate.SQL: warn

maze:
  name: data-ohlcvdatasets
  storage:
    ohlcvdatasets:
      enabled: false
      bucket: local-ohlcv-datasets
      prefix: ohlcv-datasets
      region: eu-central-1
      endpoint: http://localhost:4566
      force-path-style: true

spring:
  datasource:
    enabled: true
    default:
      url: jdbc:postgresql://localhost:5432/local
      username: local
      password: local
  cloud:
    aws:
      region:
        static: eu-central-1
      credentials:
        access-key: localstackAccessKeyId
        secret-key: localstackSecretAccessKey
